//
// MessageResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MessageResponse: Codable {

    public var success: Bool

    public init(success: Bool) {
        self.success = success
    }


}

