//
// Status.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Status: Codable {

    public var status: String
    public var details: [String]
    public var timestamp: String

    public init(status: String, details: [String], timestamp: String) {
        self.status = status
        self.details = details
        self.timestamp = timestamp
    }


}

